name: x64 Linux AArch64

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    name: >-
      ubuntu-24.04-arm

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Print gcc version
        run: |
          gcc -v

      - name: Prepare boinc libraries
        run: |
          mkdir boinc_build
          cd ./boinc_build
          git clone --depth 1 https://github.com/BOINC/boinc.git
          cd ./boinc
          ./_autosetup
          ./configure --disable-server --disable-manager --disable-client --enable-static CXXFLAGS="-O3 "
          make -j

      - name: Run make
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DNBODY_DEV_OPTIONS=ON -DNBODY_GL=OFF -DNBODY_STATIC=ON -DENABLE_CURSES=OFF -DSEPARATION_OPENCL=OFF -DBOINC_APPLICATION=ON -DNBODY_CRLIBM=OFF -DSEPARATION=OFF -DDOUBLEPREC=ON -DNBODY_OPENMP=ON -DNBODY_OPENCL=OFF -DAUTODIFF=OFF -DAUTODIFF_LOG=OFF ..
          make -j

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nbody
          retention-days: 1
          path: |
            ./build/bin/milkyway_nbody
